name             'revel-deploy-cookbook'
maintainer       'Daniel Klopp'
maintainer_email 'dsklopp@gmail.com'
license          'All rights reserved'
description      'Installs/Configures revel-deploy-cookbook'
long_description 'Installs/Configures revel-deploy-cookbook'
version          '0.1.0'

depends 'apt'
depends 'golang'